spring:
  datasource:
    url: jdbc:h2:file:./inventory;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: off
